### ISSUE TITLE
save support on windows

### ISSUE THREAD

**Issue by seanbreckenridge** [seanbreckenridge/browserexport#22]
Essentially, just need to install these browsers on Windows and see where they typically install to, add the corresponding paths to each [Browser](https://github.com/seanbreckenridge/browserexport/tree/master/browserexport/browsers) file in the `data_directories` function

**Comment by seanbreckenridge** [comment]
Am unsure of if this would be better do code for in WSL or in the windows cmd shell?

I pretty much only use WSL, so would probably use something like `wslvar USERPROFILE` to get the users `C:` dir and then perform a find relative to that?

If anyone has any opinions on how to do this, let me know

**Comment by MTRNord** [comment]
At least for Firefox the base folder is `%appdata%\Mozilla\Firefox\` on my system and the database being in `Profiles\<profile>` in case this help people coming along in the future

**Comment by seanbreckenridge** [comment]
can use `os.path.expandvars`, like in #40

**Comment by seanbreckenridge** [comment]
will close this in favor of #42 and #44
