### ISSUE TITLE
support exporting history with snap installs

### ISSUE THREAD

**Issue by karlicoss** [seanbreckenridge/browserexport#32]
Seems that in ubuntu 22.04 the default firefox installation in via Snap, so the profile dir is in `~/snap/firefox/common/.mozilla/firefox` :eyes:  

I might fix it myself later, just leaving it here in case someone else is looking -- likely needs a fix somewhere around this line, e.g. if could take a sequence of paths and go through them

https://github.com/seanbreckenridge/browserexport/blob/e7f36b6f7090877620be74180373bc81a326a2b6/browserexport/browsers/firefox.py#L53

Btw IIRC it's been similar for chromium for a while, but haven't used chrome for ages, so not sure

**Comment by seanbreckenridge** [comment]
Ah right

I think will probably extend the handle_glob function to allow accepting multiple possible paths [here](https://github.com/seanbreckenridge/browserexport/blob/e7f36b6f7090877620be74180373bc81a326a2b6/browserexport/browsers/common.py#L98), so would probably do something like:

```
    @classmethod
    def data_directory(cls) -> Union[Path, Sequence[Path]]:
        return handle_path(
            {
                "linux": ("~/.mozilla/firefox/", "~/snap/firefox/common/.mozilla/firefox"),
                "darwin": "~/Library/Application Support/Firefox/Profiles/",
            },
            browser_name=cls.__name__,
        )

    @classmethod
    def locate_database(cls, profile: str = "*") -> Path:
        dd: Path = cls.data_directory()
        return handle_glob(dd, profile + "/places.sqlite")
```

and then `handle_glob` checks if its a tuple/list and searches each of those to see if it can find it

Doesnt have to be exactly this, but something like it
