### ISSUE TITLE
new browsers - firefox forks adress in windows 10

### ISSUE THREAD

**Issue by leao-nardo** [seanbreckenridge/browserexport#42]
librewolf
\AppData\Roaming\librewolf\Profiles\

floorp
\AppData\Roaming\Floorp\Profiles\

firefox - in the program it has a dot in the .mozzila here is without it maybe it changed already
\AppData\Roaming\Mozilla\Firefox\Profiles\

and '*/places.sqlite'  //like in firefox

**Comment by seanbreckenridge** [comment]
Hi yeah, these can probably be added. I will install librewolf and floorp on linux to see if the default firefox schema works to parse their history or if they've changed their db schema like palemoon had

Im not as familiar with windows paths, but like #40, I think I should be able to locate these by using `expandvars("%localappdata%")`:

`"win32": path.expandvars("%localappdata%\\Google\\Chrome\\"),`

Though, the ones in #40 seem to be using `%localappdata%` which afaik expands to `\AppData\Local` ([referencing this](https://stackoverflow.com/questions/13184414/how-can-i-get-the-path-to-the-appdata-directory-in-python)), and not `%appdata%` which expands to `\AppData\Roaming` like you posted

Seems these are artifacts of Vista user management and these folders could be in either `%appdata%` or `%localappdata%` depending on how the user has stuff configured, I suppose we could check both?

**Comment by seanbreckenridge** [comment]
installed em and the firefox sqlite queries work to detect/parse the visits out of em

If youre not sure on the appdata/localappdata issue I can do some more research/check both paths, let me know

**Comment by seanbreckenridge** [comment]
Will setup a Windows vm tonight to see if I can test

**Comment by leao-nardo** [comment]
yeah here in mine its all in roaming . but if may sometimes install in local then putting both may be better ans it doesnt harm performance looking 2 paths . as its a utility of not frequent use , generally one time in months , better to just cover all.

**Comment by seanbreckenridge** [comment]
Yep makes sense

Will test it in the VM and then add a helper to support checking both paths
on windows

**Comment by seanbreckenridge** [comment]
Ok, I've pushed changes to the 'firefox-derivatives-windows' branch, could you test floorp/librewolf/firefox with:

```
git clone https://github.com/seanbreckenridge/browserexport
cd browserexport
git checkout firefox-derivatives-windows
python3 -m pip install .
python3 -m browserexport --debug save -b firefox -t .
python3 -m browserexport --debug save -b librewolf -t .
python3 -m browserexport --debug save -b floorp -t .
```

**Comment by seanbreckenridge** [comment]
Tested in the VM and merged into master:

```
```
