### ISSUE TITLE
how to backup list link plugins?

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [seanbreckenridge/browserexport#52]
Hi. i have a bunch of cent browser plugins soon i am moving to a new gmail / i have a bunch of plugins , a lot of them. 
I need to make a backup in the form of links.
example picture, just a list of my extensions as links from chrome store.

![sshot-002](https://github.com/seanbreckenridge/browserexport/assets/73518754/b2c32b26-0d16-424d-8783-b971ccf2ea65)

**Comment by seanbreckenridge** [comment]
Not really something this project is meant to backup (this is just meant to backup your history), but afaik plugins don't store their URLs? If cent is chromium based, you can go to `/wherever/cent/stores/browser/history/Default/Extensions` and see the actual installations

Might be able to find more info here: https://superuser.com/questions/420900/backup-extensions-bookmarks-and-other-customizations-from-google-chrome

I dont try to deal with any of this and just keep a list of all of my plugins (though I know thats not what youre looking for)

https://sean.fish/d/firefox_addons.txt?dark

**Comment by subsubsubsubsubsub** [comment]
Спасибо! Брат

**Comment by seanbreckenridge** [comment]
Will close then, as its not really relevant to the project
